kind: ENC[AES256_GCM,data:d1iqSEoZ,iv:2yMTC6VJ7iNh1evmpzeqa9XaONdLeNGtT5IHvBG1yMs=,tag:nsGOoZdDlFCsJ8NX1vahww==,type:str]
ansible_user: ENC[AES256_GCM,data:aP8=,iv:1KXRGpW2UoRdDz/eA8Xwj5hOILwCqE6wYq0whH6ab6c=,tag:PJJ9rly70vkyzJXvMeSHPA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:fBK6LvFQHrfunZHPqcHD,iv:aUBejmGctcRCjnxOlTpLZkbu3NYIOMtsI7ct1I77+ew=,tag:fJl7+E2MeL+nDRkYCa+3wQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ektnty768fg3wmhhepcg760zvxspclsd0qkfxa2f9ly8fgslyausrasx94
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtckNGTGZjc0pKTXRCQXF1
            SzNqMEdPYk5mOGY4YmNzbE9TQ1hPLzhkK1NnCmZWSHRwYysvWDJFQkwwb2Q3Q2Jk
            QW15aFUzbjQ1OGY3R2JiN0kzV2lzajAKLS0tIHh0RnBMQTB4ZFo5UDJudCtiaklh
            a0x0VzhUK0tibk81TlVQRkhINGt6bTAKBqvIKqHhzHs6ddQmtwn6YwnYCsbIWXGf
            LcbdZ6pmfQqoP8inBKK9SI99UBaQXVS+l/wmu5PJh9FUViZT4pUBHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-11T23:23:47Z"
    mac: ENC[AES256_GCM,data:N3/zwu3/GivmyoBCgWfOtkVw/ZBTt5xHTPR7yvGNhBkoVVLyVc2xKqKPqRb+5Tp25IaX3oaxbGaJKZwxHd4QTWMSPv5YBz2XhesmadYVxmwyovw7Jp0Das9TWZ8SRhFQXHkC5wxPIHahnerwjWTuGzAWxdUAvFCfVBCcGAk77NM=,iv:rinf1TmC3UUeydjWsNfcN0e9raSI6J0xGRHUELkg6L4=,tag:paRqWcZPeIxbXKZhcty2uA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
