---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Los_Angeles"
  KUBE_VIP_ADDR: "172.22.22.19"
  METALLB_LB_RANGE: "172.22.22.20-172.22.22.30"
  METALLB_K8S_GATEWAY_ADDR: "172.22.22.20"
  METALLB_INGRESS_ADDR: "172.22.22.21"
