apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:0J+zIrhstKDy,iv:rpZuRi/x0eoDAPsP5hR5ATYoOGonIPsGYggLetmMOJE=,tag:ocX25XG0DhgJqs6mJ3NZDg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:qCQL2nkII57+JpYPy1sLFKTt,iv:8vwhkR0zdalD34AB4Ozb7qn4WHxcbl3AvLW6QRucUhI=,tag:iPXlYmQGY+FS0Hjn9QXmeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ektnty768fg3wmhhepcg760zvxspclsd0qkfxa2f9ly8fgslyausrasx94
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJc1Zoa1JEbElnNVFzd29j
            Qm1jamJpY2J6anNFeGEra0JKUHhIVTQ5QmtVCkJ4TERDTW5TOWN1OW5nNzJYZmp5
            M1ptWDdOVmYrc2hnS0g1ai8rRm5pUzQKLS0tIEwyYzVYRGFWSnZVbUs2N2d2S3V3
            c3VwUkZTVFRzeWI3N1Vsd2NJR2YwTEEKVNKFCzLrQd2EUcOpNmBPTxJm/e7vKArR
            /Xjphk/rR7/t5FW7RZVJ3fXN98RxTTBr6MCI/oHxpo0HK1bnETTj0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-12T22:52:44Z"
    mac: ENC[AES256_GCM,data:ENn8mIfvidRPyS92d2r5bU7iKIq8NumUELuAOhU1MOfVuCsDSHCxb6BGmTP6GwCaCG+SSSaj2q8ZmM+uEAreP+LAxvHR+XFj9ToVikniwfRzEyvdnMPfIDGrBwuOTeRnF6Z6vY6WJ8boWv8s4nAEtDlPev05M41iYmstnpY+skw=,iv:WZOzSuiJ4u+fyr68hNEUz0BKAp0tD6xZf+I0qmOpPFY=,tag:x0gPrewAfookL1TRX3mmnA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
